services:
  app:
    build: .
    container_name: edupresence
    volumes:
      - ./:/var/www/html
      - employee-img:/var/www/html/storage/app/public/employees
    ports:
      - "8080:80"
    networks:
      - edupresence-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9099:9090"
    # networks:
    #   - laravel

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3129:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    # networks:
    #   - laravel
    
volumes:
  employee-img:
    external: true
  grafana-storage:

networks:
  edupresence-net:
    external: true
    # Testing
