services:
  app:
    build: .
    container_name: edupresence
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Testing

  redidocs:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9099:9090"
    # networks:
    #   - laravel

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3129:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    # networks:
    #   - laravel
    
volumes:
  grafana-storage:
