services:
  app:
    build: .
    container_name: edupresence
    volumes:
      - ./:/var/www/html
      - employee-img:/var/www/html/storage/app/public/employees
    ports:
      - "8080:80"
    networks:
      - edupresence-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "eduprence.my.id:host-gateway"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - edupresence-net
    
volumes:
  employee-img:
    external: true

networks:
  edupresence-net:
    external: true
    # Testing
