services:
    app:
        build:
            args:
                user: ${DOCKER_USER}
                uid: ${DOCKER_UID}
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        container_name: apsensi-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www
        networks:
            - apsensi-network
    nginx:
        image: nginx:alpine
        container_name: apsensi-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - apsensi-network
    queue:
        build:
            args:
                user: ${DOCKER_USER}
                uid: ${DOCKER_UID}
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        container_name: apsensi-queue
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www
        command: php artisan queue:listen
        networks:
            - apsensi-network
networks:
    apsensi-network:
        driver: bridge
