services:
  app:
    build: .
    container_name: edupresence
    volumes:
      - ./:/var/www/html
      - employee-img:/var/www/html/storage/app/public/employees
    ports:
      - "8080:80"
    networks:
      - edupresence-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  employee-img:
    external: true

networks:
  edupresence-net:
    external: true
