global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'laravel-app'
    static_configs:
      - targets: ['host.docker.internal:8080'] 
      
  - job_name: 'laravel-app-local'
    static_configs:
      - targets: ['localhost:8089'] # atau ganti dengan IP/hostname container app
